apiVersion: apps/v1
kind: Deployment
metadata:
  name: authzadapter-deployment
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: authzadapter
  replicas: 1
  template:
    metadata:
      labels:
        app: authzadapter
    spec:
      restartPolicy: Always
      containers:
      - name: authn-server
        image: mymixeradapter/authzadapter:latest
        ports:
        - containerPort: 45678

---
apiVersion: v1
kind: Service
metadata:
  name: authzadapter-service
  labels:
    app: authzadapter
  namespace: istio-system
spec:
  ports:
  - name: grpc
    port: 45678
  selector:
    app: authzadapter