apiVersion: apps/v1
kind: Deployment
metadata:
  name: authzadapter-deployment
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: authzadapter
  replicas: 1
  template:
    metadata:
      labels:
        app: authzadapter
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Always
      containers:
      - name: authn-server
        image: jianshao/authzadapter:0.3.0
        ports:
        - containerPort: 45678
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: authzadapter-service
  labels:
    app: authzadapter
  namespace: istio-system
spec:
  ports:
  - name: grpc
    port: 45678
  selector:
    app: authzadapter