# handler for adapter authzadapter
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: authzhandler
  namespace: istio-system
spec:
  adapter: authzadapter
  connection:
    address: "{ADAPTER_HOST}:45678"
  params:
    pdp_host: pdp-service
    pdp_port: 8080
---

# instance for template enhencedauthz
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: authzinstance
  namespace: istio-system
spec:
  template: enhencedauthz
  params:
    subject:
      user: source.principal | request.auth.principal | ""
      groups: request.auth.claims["groups"] | ""
      properties:
        authorization_header: request.headers["authorization"] | ""
    action:
      namespace: destination.namespace | "default"
      service: destination.service.host | ""
      path: request.path | "/"
      method: request.method | "post"
      properties:
        priority_header: request.headers["x-request-priority"] | "100"
---

# rule to dispatch to handler authzhandler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: authzrule
  namespace: istio-system
spec:
  match: destination.namespace == "secured-api"
  actions:
  - handler: authzhandler.istio-system
    instances:
    - authzinstance
    name: authzhandler
  requestHeaderOperations:
  - name: x-client-id
    values:
    - authzhandler.output.clientID
  - name: x-authz-type
    values:
    - authzhandler.output.authzType
---